#!/bin/bash
echo "🌪️  HailyDB SPC Historical Backfill System"
echo "=========================================="
echo ""
echo "Available Commands:"
echo ""
echo "1. Start with August 2025 (recommended):"
echo "   python3 spc_backfill_runner.py"
echo ""
echo "2. Custom month backfill:"
echo "   python3 spc_backfill.py --year YYYY --month M"
echo ""
echo "3. Custom date range:"
echo "   python3 spc_backfill.py --start-date YYYY-MM-DD --end-date YYYY-MM-DD"
echo ""
echo "4. Quick test (last 3 days):"
echo "   python3 spc_backfill.py --start-date 2025-08-08 --end-date 2025-08-10 --delay 1"
echo ""
echo "=========================================="
